// VictorAI screens. Retro pink terminal styling; the waveforms are the one
// sleek, animated element against it.

import { useState } from 'react'
import type { ClipPlayer } from '../lib/audio/clipPlayer'
import type { GridClip } from '../types'
import { RIDDLE, ESCAPE } from '../game/content'
import { ClipCard } from './ClipCard'
import { Confetti } from './Confetti'

function Title() {
  return <h1 className="v-title">VictorAI</h1>
}

function NextButton({ onClick, disabled, label = 'next >' }: {
  onClick: () => void
  disabled?: boolean
  label?: string
}) {
  return (
    <button className="v-next" onClick={onClick} disabled={disabled}>
      {label}
    </button>
  )
}

// ---------------------------------------------------------------------------
export function GridScreen({ player, clips, onMark, onNext }: {
  player: ClipPlayer
  clips: GridClip[]
  onMark: (id: string, mark: boolean) => void
  onNext: () => void
}) {
  const answered = clips.every((c) => c.mark !== null)
  const left = clips.slice(0, 5)
  const right = clips.slice(5, 10)
  return (
    <div className="v-screen v-grid-screen">
      <Title />
      <p className="v-intro">
        The Chief Exec has been hacked! Click on each audio clip to listen.
        You need to decide which 5 are truly from Victoria and which 5 have
        been generated by AI. Is the audio clip real?
      </p>
      <div className="clip-grid">
        <div className="clip-col">
          {left.map((c, i) => (
            <ClipCard key={c.id} player={player} clip={c} index={i} onMark={(m) => onMark(c.id, m)} />
          ))}
        </div>
        <div className="clip-col">
          {right.map((c, i) => (
            <ClipCard key={c.id} player={player} clip={c} index={i + 5} onMark={(m) => onMark(c.id, m)} />
          ))}
        </div>
      </div>
      <div className="v-footer">
        {!answered && <span className="v-hint">Mark all ten to continue…</span>}
        <NextButton onClick={onNext} disabled={!answered} />
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
export function ScoreScreen({ correct, total, onNext }: {
  correct: number
  total: number
  onNext: () => void
}) {
  return (
    <div className="v-screen v-score-screen">
      {correct === total && <Confetti />}
      <Title />
      <p className="v-intro">
        You correctly selected <strong>{correct}</strong> of the {total} real
        clips from Victoria!
      </p>
      <div className="v-big-score">{correct}/{total}</div>
      <p className="v-body">
        The genuine clips aren't random — listen again, and they lead somewhere.
        The fakes were only ever trying to throw you off.
      </p>
      <div className="v-footer">
        <NextButton onClick={onNext} />
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
export function RiddleScreen({ player, realClips, onSolved }: {
  player: ClipPlayer
  realClips: GridClip[]
  onSolved: () => void
}) {
  const [picked, setPicked] = useState<string | null>(null)
  const [wrong, setWrong] = useState(false)

  const choose = (id: string) => {
    setPicked(id)
    const opt = RIDDLE.options.find((o) => o.id === id)
    if (opt?.correct) {
      player.stop()
      window.setTimeout(onSolved, 500)
    } else {
      setWrong(true)
    }
  }

  return (
    <div className="v-screen v-riddle-screen">
      <Title />
      <p className="v-intro">Listen carefully again. What message is Victoria trying to communicate?</p>
      <div className="riddle-layout">
        <div className="riddle-clips">
          {realClips.map((c, i) => (
            <ClipCard key={c.id} player={player} clip={c} index={i} onMark={() => {}} readOnly />
          ))}
        </div>
        <div className="riddle-options">
          <p className="riddle-q">{RIDDLE.question}</p>
          {RIDDLE.options.map((o) => (
            <button
              key={o.id}
              className={
                'riddle-opt' +
                (picked === o.id ? (o.correct ? ' riddle-opt-right' : ' riddle-opt-wrong') : '')
              }
              onClick={() => choose(o.id)}
            >
              <span className="riddle-letter">{o.id}.</span> {o.label}
            </button>
          ))}
          {wrong && <p className="riddle-wrong-note">Not quite — play the real clips again and listen to how each one starts.</p>}
        </div>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
export function EscapeScreen({ onNext }: { onNext: () => void }) {
  return (
    <div className="v-screen v-escape-screen">
      <Confetti />
      <Title />
      <p className="v-intro">Cracked it. Victoria's hidden message was:</p>
      <div className="codeword">{ESCAPE.codeword}</div>
      <p className="v-body">Your escape-room letter is</p>
      <div className="escape-letter">{ESCAPE.letter}</div>
      <p className="v-body v-flavour">{ESCAPE.flavour}</p>
      <div className="v-footer">
        <NextButton onClick={onNext} label="what just happened? >" />
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
export function DebriefScreen({ onRestart }: { onRestart: () => void }) {
  return (
    <div className="v-screen v-debrief-screen">
      <Title />
      <h2 className="v-h2">Could you tell the difference?</h2>
      <p className="v-body">
        AI voice-cloning technology can study recordings of a person speaking
        and learn the patterns in their voice — their accent, rhythm, tone and
        pronunciation. It can then generate new speech that sounds as though the
        person said words they never actually spoke.
      </p>
      <p className="v-body">
        Voice cloning can be useful for entertainment, accessibility and
        translation, but it can also be misused. Criminals may imitate a family
        member, colleague or senior leader to request money, passwords,
        confidential information or urgent action. A convincing voice is no
        longer proof that the caller is genuine.
      </p>
      <h2 className="v-h2">Stop. Check. Confirm.</h2>
      <p className="v-body">
        Be cautious when a call or voice message is unexpected, urgent or asks
        you to ignore normal procedures:
      </p>
      <ul className="v-list">
        <li>Do not share passwords, security codes or sensitive information.</li>
        <li>Do not transfer money based only on a voice request.</li>
        <li>End the call and contact the person using a trusted number you already have.</li>
        <li>Ask a question or use a private phrase that an impersonator would not know.</li>
        <li>Report suspicious messages or calls through the correct security channel.</li>
      </ul>
      <h2 className="v-h2 v-h2-final">Listen carefully — but always verify another way.</h2>
      <div className="v-footer">
        <NextButton onClick={onRestart} label="play again >" />
      </div>
    </div>
  )
}
